### ISSUE TITLE
Even though BATCH_SIZE=1 but worker dequeue 2 task while still first task not finished.

### ISSUE THREAD

**Issue by shalinitrivedi1** [conductor-sdk/conductor-go#119]
**Issue:**

Even though batch size is set as 1. Noticed that 2 tasks were dequeued by the worker.

**RCA:**

There is a race between getAvailableWorkerAmount() and executeAndUpdateTask() in workOnce() code. Here are the sequence of events:

**STEPS to reproduced**
BATCH_SIZE is set to 1 in my case.

1. More than 1 tasks are present in the work queue.
2. Worker is started and a task is dequeued and processing started but not finished yet for first task.
3. But Worker dequeuing another task without checking as first task still running

**FIX** 
Conductor GO SDK need to fix and below PR raised for same . Please take a look and merge it and new release .or let me know whats the process to get it fixed on condutor-go as its blocking our release.
https://github.com/conductor-sdk/conductor-go/pull/118

**conductor version**
conductor-go v1.3.2

**Note:** 
it seems like the Java SDK client has moved away from this design and using TaskRunnerConfig to poll for tasks. But go client isn't quite there yet. But as this is blocking our release we fixed this issue on conductor-go client in below PR
https://github.com/conductor-sdk/conductor-go/pull/118

**Comment by shalinitrivedi1** [comment]
@v1r3n @c4lm  please update when I can get new version of conductor-go-sdk as PR-118 already merged to main

**Comment by v1r3n** [comment]
Closing this since the release was already out.
