### ISSUE TITLE
Parse JSON Workflow

### ISSUE THREAD

**Issue by sounddroid** [conductor-sdk/conductor-go#82]
Hello! Just wondering if there is a function available to parse a JSON workflow into a typed ConductorWorkflow object? Thank you!

**Comment by gardusig** [comment]
Hey @sounddroid! Given that `ConductorWorkflow` will inherit most properties from internal models by [PR](https://github.com/conductor-sdk/conductor-go/pull/76), it may be quite simple to achieve a json conversion. I will let this issue open until the PR gets finished.

You can also accomplish by doing something like:

```go
bytes := json.Marshall(jsonWorkflow)
var workflowDef model.WorkflowDef
json.Unmarshall(bytes, workflowDef)
```

**Comment by sounddroid** [comment]
Thank you @gardusig ! I'll give it a go. I figured it would be something simple like that.

**Comment by v1r3n** [comment]
Closing as its s stale issue.  Please re-open if required.
