### ISSUE TITLE
RegisterTaskDef without any retry

### ISSUE THREAD

**Issue by cycade** [conductor-sdk/conductor-go#87]
Hi, just wonder is there any way to create a task with retryCount=0? Cause`retryCount` is an "omitempty" attribute.

Also try some other value like retryCount=-1 etc. however there's validation on server side

Maybe using *int32 for retryCount is a better way in TaskDef?

**Comment by gardusig** [comment]
Hey @cycade, even though I agree with you, it may be tricky to evaluate each parameter from each model. We generally opt for a shortcut, which is generating all the code between a client and a server. Also, if aiming for validation at both sides, it creates an brand new (unnecessary) maintenance - to keep the client validation up to date with the server validation.

Specifically saying about `retryCount` - how would you benefit from a pointer? IMO - It can bring compatibility issues for other users while not bringing much value. The server does a great job at validating each parameter and the client should just inform you about it :)

**Comment by cycade** [comment]
> 

Yes, I agree with you in compatibility issue of the change. So my point is, how can I create a task that would never retry?

**Comment by gardusig** [comment]
Now I got it, if you set its value to zero, its going to interpret as no value defined, instead of sending with value 0. Let me see a few options, if needed I'll send a commit soon :) Thanks for the feedback!

**Comment by gardusig** [comment]
Hey @cycade, I think your issue should be solved by [v1.2.24](https://github.com/conductor-sdk/conductor-go/releases/tag/v1.2.24), please let us know in case it did not work out :)
