### ISSUE TITLE
Writing workers in go

### ISSUE THREAD

**Issue by sandeep540** [conductor-sdk/conductor-go#93]
Hi ,

I am running conductor as docker-compose in local, and wrote a simple program in go for worker - https://github.com/sandeep540/netflix_conductor

It's running, but not completing task and there are no logs, can you please help me in debuggin where am I going wrong,

P.S: I got it working with java, but we have requirement with go

**Comment by manan164** [comment]
Hi @sandeep540 , Do you see any error in polling task `task_11`?

**Comment by sandeep540** [comment]
No errors

**Comment by sandeep540** [comment]
One thing I noticed is even when I change the conductor url from "http://localhost:8080/api/". to some invalid address, the worker still starts, not sure if thats the expected behavior

**Comment by sounddroid** [comment]
> One thing I noticed is even when I change the conductor url from "http://localhost:8080/api/". to some invalid address, the worker still starts, not sure if thats the expected behavior

This also surprised me as well. That is what I have in my code but it took me a while to figure out.

**Comment by supriyanta** [comment]
Remove the last slash `/` from the conductor server URL. 
For logging, you can look at this [section](https://github.com/conductor-sdk/conductor-go#setup-logging).

**Comment by sandeep540** [comment]
it worked with "http://localhost:8080/api"

**Comment by sandeep540** [comment]
thanks @supriyanta
