### ISSUE TITLE
Task Output not coming Up

### ISSUE THREAD

**Issue by sandeep540** [conductor-sdk/conductor-go#96]
Hi

I am using an API - workflowExecutor.UpdateTask() to pass task status and output, but output is not going to conductor

It's failing at
https://github.com/conductor-sdk/conductor-go/blob/ff3da476b5303001cbc7b9604ac1f22f35d9c279/sdk/model/task_execute_function.go#L70 and returning nil

**Comment by supriyanta** [comment]
Hi @sandeep540 can you please show, how you are using the `updateTask` function?

**Comment by sandeep540** [comment]
Here is the code

```
			err := workflowExecutor.UpdateTask("08abf618-0686-4ead-ae4b-f3ddd2f8c1bd", "40815678-4809-49a0-b3e5-e035e0a2286d", workflow_model.CompletedTask, {"cake":"yummy"})
			if err != nil {
				fmt.Println(err.Error())
			}
```

**Comment by supriyanta** [comment]
Hi @sandeep540 the `updateTask` api can change the state and output only when you use it during the workflow is in SCHEDULED state.

**Comment by sandeep540** [comment]
@supriyanta Yes, the workflow instance is running and particular task is in "Pending" state, From Swagger API, I am able to set the output , not from go SDK

**Comment by sandeep540** [comment]
Oh I was passing output as string, need to change it to map[string], now it worked
